// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbupaH1VHxuuW_dvPnRAMFswqQHbZzE9E',
    appId: '1:849076902660:android:5d4d3401f2eccd84fb8e51',
    messagingSenderId: '849076902660',
    projectId: 'fir-utils-5b19b',
    storageBucket: 'fir-utils-5b19b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrKgwijejE_aKHyUXjUU7-T3_ZuvGFf0',
    appId: '1:849076902660:ios:17e605c8a5c8f5f8fb8e51',
    messagingSenderId: '849076902660',
    projectId: 'fir-utils-5b19b',
    storageBucket: 'fir-utils-5b19b.appspot.com',
    iosClientId: '849076902660-5ef63soov5ju440at50q5vur39cp8qmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrKgwijejE_aKHyUXjUU7-T3_ZuvGFf0',
    appId: '1:849076902660:ios:17e605c8a5c8f5f8fb8e51',
    messagingSenderId: '849076902660',
    projectId: 'fir-utils-5b19b',
    storageBucket: 'fir-utils-5b19b.appspot.com',
    iosClientId: '849076902660-5ef63soov5ju440at50q5vur39cp8qmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
